SELECT CLIENT.CLIENT_ID, SUM(CHASM_SALE.SALE_TOTAL) AS SALE_TOTAL
FROM CLIENT
	INNER JOIN CHASM_SALE ON CLIENT.CLIENT_ID = CHASM_SALE .CLIENT_ID
WHERE CLIENT.CLIENT_ID in (1001, 1021, 1081)
GROUP BY CLIENT.CLIENT_ID